import type { Finding } from '../plugins/research/types.js';
import type { HtmlProfile } from './html-profile.js';

export interface Check {
  name: string;
  ok: boolean;
  /** Blocking checks make the verdict `blocked`; advisory ones make it `revise`. */
  blocking: boolean;
  score?: number;
  detail: string;
  findings: string[];
}

export interface Scorecard {
  verdict: 'pass' | 'revise' | 'blocked';
  wordCount: number;
  checks: Check[];
}

/**
 * A real inline image — an `<img ...src=...>` tag, not just the substring
 * "img" appearing somewhere in the markup. One rule, one definition:
 * `create_post`'s images enforcement (src/tools/post-tools.ts) imports this
 * exact check rather than re-deriving its own regex, so the two never drift
 * apart the way `SLUG_PATTERN` and `IMAGE_LOOKS` once did.
 */
export function hasInlineImage(html: string): boolean {
  return /<img\s[^>]*src\s*=/i.test(html);
}

const BANNED = [
  'delve',
  'transformative',
  'seamless',
  'seamlessly',
  'robust',
  'revolutionary',
  'tapestry',
  'testament',
  'unlock the power',
  "in today's world",
  'ever-evolving',
  'ever-changing',
  'navigate the landscape',
  'the landscape of',
  'dive deep',
  'game-changer',
  'paradigm shift',
  'leverage the power',
];

const BANNED_PATTERNS: Array<[RegExp, string]> = [
  [/it['’]s not just [^,.]{2,40}, it['’]s/i, '"it\'s not just X, it\'s Y" construction'],
  [/\bnot only [^,.]{2,40} but also\b/i, '"not only X but also Y" construction'],
];

const stripTags = (html: string): string =>
  html
    .replace(/<[^>]*>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

function sentences(text: string): string[] {
  return text
    .split(/(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter((s) => s.split(/\s+/).length >= 3);
}

function stdev(ns: number[]): number {
  if (ns.length < 2) return 0;
  const mean = ns.reduce((a, b) => a + b, 0) / ns.length;
  return Math.sqrt(ns.reduce((a, b) => a + (b - mean) ** 2, 0) / ns.length);
}

/**
 * The feature image, which lives outside the HTML and so is invisible to the
 * scorer unless it is passed in.
 *
 * `title` is only used to catch alt text copy-pasted from the headline.
 */
export interface FeatureImageInput {
  url?: string;
  alt?: string;
  title?: string;
}

/** lowercase, strip punctuation, collapse whitespace — for comparing alt to title. */
function normalise(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Alt text that just repeats the headline, which is the default failure mode.
 *
 * Containment either way rather than equality, since "AI agents in fintech"
 * pasted into alt is the same failure as the full title with two extra words.
 * Deliberately NOT a keyword overlap test — alt text SHOULD share vocabulary
 * with the article, and a check that fired on that would train people to write
 * worse alt text to satisfy it.
 */
function restatesTitle(alt: string, title: string): boolean {
  const a = normalise(alt);
  const t = normalise(title);
  if (a === '' || t === '') return false;
  return a.includes(t) || t.includes(a);
}

/**
 * Decode the small set of HTML entities that legitimately appear inside an
 * href written by hand or generated by a template. `&amp;` is the common
 * one: a raw `&` inside an attribute value is invalid HTML, so any
 * correctly-written link with more than one query parameter uses `&amp;`
 * between them. Without decoding it first, `sameUrl` sees `utm_source=x
 * &amp;utm_campaign=y` as a single param named `amp;utm_campaign` and the
 * match fails — reporting a correctly-cited source as invented, which is
 * exactly the false positive this check exists to avoid.
 */
function decodeHtmlEntities(s: string): string {
  return s
    .replace(/&amp;/gi, '&')
    .replace(/&quot;/gi, '"')
    .replace(/&#0*39;|&apos;/gi, "'")
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>');
}

/**
 * Compare two URLs the way a reader would: same page, however it was linked.
 *
 * Host case, a leading `www.`, http vs https, a trailing slash, campaign
 * parameters, and query-parameter order are all noise a writer legitimately
 * introduces by copying a link out of a search result or retyping it by
 * hand. Matching on the raw string would report a correctly-cited source as
 * invented, which is worse than not checking — it would train writers to
 * distrust the check.
 *
 * NOT normalised: percent-encoding differences in the path (`%70` vs `p`).
 * `URL` itself normalises some of this, but a correct general fix needs a
 * full decode/re-encode pass, and a half-solved version risks silently
 * un-checking a genuine path difference. Left as a known gap.
 */
function sameUrl(raw: string): string {
  try {
    const u = new URL(raw);
    u.hostname = u.hostname.toLowerCase().replace(/^www\./, '');
    u.protocol = 'https:';
    u.hash = '';
    for (const key of [...u.searchParams.keys()]) {
      if (key.toLowerCase().startsWith('utm_') || key.toLowerCase() === 'fbclid') u.searchParams.delete(key);
    }
    u.searchParams.sort();
    u.pathname = u.pathname.replace(/\/+$/, '') || '/';
    return u.toString().replace(/\/$/, '');
  } catch {
    // Not parseable as a URL — compare it as itself rather than dropping it.
    return raw.trim().toLowerCase().replace(/\/$/, '');
  }
}

export function scoreDraft(
  html: string,
  profile: HtmlProfile,
  feature?: FeatureImageInput,
  findings?: readonly Finding[],
): Scorecard {
  const text = stripTags(html);
  const words = text ? text.split(/\s+/).length : 0;
  const checks: Check[] = [];

  // --- AI-tell lexicon (advisory) ---
  const lexHits: string[] = [];
  for (const word of BANNED) {
    const re = new RegExp(`\\b${word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi');
    const n = (text.match(re) ?? []).length;
    if (n > 0) lexHits.push(`"${word}" ×${n}`);
  }
  for (const [re, label] of BANNED_PATTERNS) if (re.test(text)) lexHits.push(label);
  checks.push({
    name: 'ai_lexicon',
    ok: lexHits.length === 0,
    blocking: false,
    detail: lexHits.length === 0 ? 'No AI-tell phrasing' : `${lexHits.length} AI-tell phrase(s)`,
    findings: lexHits,
  });

  // --- Burstiness (advisory) ---
  const lengths = sentences(text).map((s) => s.split(/\s+/).length);
  const sd = Number(stdev(lengths).toFixed(2));
  checks.push({
    name: 'burstiness',
    ok: sd >= 6,
    blocking: false,
    score: sd,
    detail: `Sentence-length sd ${sd} words (target >= 6)`,
    findings: sd >= 6 ? [] : ['Sentences are too uniform — break some short, let others run long'],
  });

  // --- Paragraph uniformity (advisory) ---
  const paraSentenceCounts = [...html.matchAll(/<p[^>]*>(.*?)<\/p>/gis)]
    .map((m) => sentences(stripTags(m[1] ?? '')).length)
    .filter((n) => n > 0);
  let run = 1;
  let worstRun = paraSentenceCounts.length > 0 ? 1 : 0;
  for (let i = 1; i < paraSentenceCounts.length; i++) {
    run = paraSentenceCounts[i] === paraSentenceCounts[i - 1] ? run + 1 : 1;
    worstRun = Math.max(worstRun, run);
  }
  checks.push({
    name: 'paragraph_uniformity',
    ok: worstRun <= 4,
    blocking: false,
    score: worstRun,
    detail: `Longest run of identically shaped paragraphs: ${worstRun} (max 4)`,
    findings:
      worstRun > 4 ? [`${worstRun} consecutive paragraphs have the same sentence count`] : [],
  });

  // --- Evidence density (advisory) ---
  const figures = (text.match(/\b\d[\d,.]*\s?(%|percent|x\b|million|billion|bn|k\b)/gi) ?? []).length;
  const links = (html.match(/<a\s[^>]*href="https?:/gi) ?? []).length;
  const evidence = figures + links;
  const needed = Math.max(1, Math.ceil(words / 250));
  checks.push({
    name: 'evidence_density',
    ok: evidence >= needed,
    blocking: false,
    score: evidence,
    detail: `${figures} figure(s) + ${links} citation link(s) = ${evidence}; need ${needed} for ${words} words`,
    findings: evidence >= needed ? [] : ['Add concrete figures or cite named sources'],
  });

  // --- Experience markers (advisory) ---
  //
  // Matching is deliberately tolerant of natural prose: an auxiliary or adverb may sit
  // between the pronoun and the verb ("I have watched", "we very nearly lost"), and the
  // comma after a year is optional ("In 2023 we bid..."). Requiring exact adjacency
  // produced false negatives on writing that was plainly first-hand.
  //
  // **This list has to agree with what the brief actually instructs**, and once
  // it did not. `PERSONA_PRESENCES` in `dimensions.ts` teaches an author to
  // show seniority through the room rather than the résumé, and gives
  // "We killed the pilot in week six." and "The team pushed back hard on that."
  // as its worked examples — neither of which the original verb list matched.
  // A real 1,000-word draft written to that instruction scored **zero**
  // first-hand moments. One rule, one definition: a construction the brief
  // teaches is a construction this check must recognise, and the suite pins
  // that by running the brief's own examples through this regex.
  //
  // Three shapes are recognised. A first-person actor doing something
  // (a much wider verb list than before, all past-tense operational acts); a
  // named party in the room acting on you, which is how the résumé-free
  // variants carry authority; and a visible change of mind, which the
  // "Think on the page" texture asks for by name.
  const ANECDOTE = new RegExp(
    [
      '\\bwhen (?:I|we)\\b',
      '\\bone client\\b',
      '\\ba client\\b',
      '\\blast (?:year|month|week|quarter)\\b',
      '\\bin \\d{4},? (?:I|we)\\b',
      // "in week six", "by month three" — the scale markers a real project has.
      '\\b(?:in|by) (?:week|month|sprint|quarter) (?:\\d+|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)\\b',
      // A visible correction of your own past view. "For years I called this a
      // tooling problem." "I used to treat this as a change-management problem."
      '\\b(?:I|we)(?:\\s+\\w+){0,2}\\s+used to\\b',
      '\\bfor years (?:I|we)\\b',
      // Someone else in the room, acting. This is the whole mechanism of the
      // "Through the room, not the résumé" variant.
      '\\b(?:the|our) (?:team|client|board|vendor|customer|engineers?|buyer|partner|sponsor|regulator)\\b[^.!?]{0,60}?\\b(?:pushed|signed|refused|asked|agreed|balked|walked|escalated|rejected|approved|cancelled|complained|insisted|objected|overruled|blocked)\\b',
      // A first-person operational act.
      '\\b(?:I|we)(?:\\s+\\w+){0,2}\\s+(?:once|learned|watched|shipped|rebuilt|rewrote|regret|regretted|lost|bid|delivered|priced|misjudged|underestimated|inherited|killed|scrapped|cut|hired|fired|fixed|built|ran|sat|chose|picked|pushed|argued|told|asked|sold|quoted|walked|refused|approved|signed|rejected|missed|spent|wrote|called|treated|moved|stopped|started|launched|paused|reverted|migrated|onboarded|billed|estimated|scoped|shut|pulled|rolled)\\b',
    ].join('|'),
    'gi',
  );

  const firstPerson = (text.match(/\b(I|we|my|our)\b/g) ?? []).length;
  const anecdote = (text.match(ANECDOTE) ?? []).length;
  const halfway = Math.floor(text.length / 2);
  const lateAnecdote = new RegExp(ANECDOTE.source, 'i').test(text.slice(halfway));
  // `firstPerson` was computed and reported but never gated on anything, so an
  // article with no persona voice at all could still pass this check on
  // anecdote count alone. The brief makes first person a CRITICAL REQUIREMENT
  // ("Write in FIRST PERSON as <name>"), so zero of it is not a style
  // preference — it is the signature of a draft written without the brief,
  // which is exactly how generic articles reach publication.
  const expOk = anecdote >= 2 && lateAnecdote && firstPerson > 0;
  checks.push({
    name: 'experience_markers',
    ok: expOk,
    blocking: false,
    score: anecdote,
    detail: `${anecdote} concrete first-hand moment(s), ${firstPerson} first-person reference(s); second half has one: ${lateAnecdote}`,
    findings: expOk
      ? []
      : [
          firstPerson === 0
            ? 'No first-person voice anywhere — the brief requires the article be written in first person as the persona. A draft with none was almost certainly written without build_writing_brief, and will read as generic no matter how good the prose is.'
            : '',
          anecdote < 2 ? 'Fewer than 2 concrete first-hand moments' : '',
          lateAnecdote ? '' : 'No first-hand moment after the midpoint',
        ].filter(Boolean),
  });

  // --- Generic opener (advisory) ---
  const opener = sentences(text).slice(0, 2).join(' ');
  const genericOpener =
    /^(in today'?s|in the (modern|current|fast-paced)|as (technology|the world|businesses)|(technology|business|the world) (is|has been) (rapidly )?(changing|evolving|transforming))/i.test(
      opener,
    );
  checks.push({
    name: 'generic_opener',
    ok: !genericOpener,
    blocking: false,
    detail: genericOpener ? 'Opening matches a stock template' : 'Opening is specific',
    findings: genericOpener ? [`Rewrite the opening: "${opener.slice(0, 90)}…"`] : [],
  });

  // --- Platform HTML validity (BLOCKING) ---
  //
  // Every rule below comes from the target platform's profile. Nothing here
  // knows what Ghost or WordPress do — that is the point. A rule baked in here
  // would be silently wrong for the other platform.
  const htmlFindings: string[] = [];
  // Human-readable display name for messages — `profile.platform` is the
  // lowercase machine id and must never be shown to a reader or writer.
  const name = profile.label;

  if (/<br\s*\/?>/i.test(html)) htmlFindings.push('<br> tag — use separate <p> tags');
  if (!profile.classAttributes && /\sclass\s*=/i.test(html)) {
    htmlFindings.push(`class attribute — ${name} discards it, the theme handles styling`);
  }
  if (profile.generatesHeadingIds && /<h[23][^>]*\sid\s*=/i.test(html)) {
    htmlFindings.push(`hand-written heading id — ${name} generates these`);
  }
  if (/<style[\s>]/i.test(html)) {
    htmlFindings.push(
      profile.inlineStyles
        ? '<style> block — use inline styles'
        : `<style> block — ${name} strips it, and inline styles too`,
    );
  }
  if (!profile.inlineStyles && /\sstyle\s*=/i.test(html)) {
    htmlFindings.push(
      `inline style attribute — ${name} strips styles for this account, so styled blocks publish unstyled. Write structural HTML only.`,
    );
  }

  // No `?? 'table'` fallback: a profile's `visualContainers` is either
  // populated by whoever built it, or (defensively) empty, in which case there
  // is no verified container to recommend and inventing one would put a tag
  // name in front of the writer that was never confirmed to survive ingest.
  const container = profile.visualContainers[0];
  // Every acceptable container, not just the best one — a writer told only
  // "table" is not told a styled blockquote works too.
  const containerOptions = profile.visualContainers.map((t) => `<${t}>`);
  const containerList =
    containerOptions.length === 0
      ? undefined
      : containerOptions.length === 1
      ? containerOptions[0]
      : containerOptions.length === 2
        ? `${containerOptions[0]} or ${containerOptions[1]}`
        : `${containerOptions.slice(0, -1).join(', ')}, or ${containerOptions[containerOptions.length - 1]}`;
  for (const m of html.matchAll(/<\s*\/?\s*([a-z0-9]+)[^>]*>/gi)) {
    const tag = (m[1] ?? '').toLowerCase();
    if (profile.unwrapped.has(tag)) {
      htmlFindings.push(
        containerList
          ? `<${tag}> is unwrapped by ${name} — its text survives but all styling is lost. Use a styled ${containerList} for visual blocks.`
          : `<${tag}> is unwrapped by ${name} — its text survives but all styling is lost.`,
      );
    } else if (!profile.preserved.has(tag)) {
      // For <br> specifically, emit the SAME string as the explicit rule above
      // rather than "disallowed tag <br>" — that lets `new Set(htmlFindings)`
      // dedupe the plain `<br>`/`<br/>`/`<br />` case to one finding, while
      // still flagging forms the narrow explicit regex misses entirely
      // (`</br>`, `<br data-x="1">`, `< br >`, `<br style="...">`).
      htmlFindings.push(
        tag === 'br' ? '<br> tag — use separate <p> tags' : `disallowed tag <${tag}>`,
      );
    }
  }

  for (const m of html.matchAll(/<a\s[^>]*href="https?:\/\/[^"]+"[^>]*>/gi)) {
    if (!/rel\s*=\s*"[^"]*noopener[^"]*"/i.test(m[0])) {
      htmlFindings.push(`external link missing rel="noopener noreferrer": ${m[0].slice(0, 70)}`);
    }
    if (!profile.keepsLinkTarget && /\starget\s*=/i.test(m[0])) {
      htmlFindings.push(`target attribute — ${name} strips it, so it is dead weight`);
    }
  }

  const rawUrl = stripTags(html.replace(/<a\s[^>]*>.*?<\/a>/gis, ''));
  if (/https?:\/\/\S+/.test(rawUrl)) htmlFindings.push('raw URL in body text — wrap it in an <a> tag');

  // A native-rebuilt blockquote is reconstructed by the platform, which throws
  // away the inline style and any inner <p>. Styling one is wasted effort that
  // publishes looking nothing like intended.
  if (profile.blockquote === 'native-rebuilt') {
    for (const m of html.matchAll(/<blockquote\b[^>]*>/gi)) {
      if (/\sstyle\s*=/i.test(m[0])) {
        htmlFindings.push(
          container
            ? `styled <blockquote> — ${name} rebuilds standalone blockquotes and discards the style and inner <p>. Use a plain <blockquote>, or a styled <${container}> if you need a specific look.`
            : `styled <blockquote> — ${name} rebuilds standalone blockquotes and discards the style and inner <p>. Use a plain <blockquote> instead.`,
        );
        break;
      }
    }
  }

  const uniqueHtmlFindings = [...new Set(htmlFindings)];
  checks.push({
    name: 'platform_html',
    ok: uniqueHtmlFindings.length === 0,
    blocking: true,
    detail:
      uniqueHtmlFindings.length === 0
        ? `${name}-compatible`
        : `${uniqueHtmlFindings.length} violation(s)`,
    findings: uniqueHtmlFindings,
  });

  // --- Structure (BLOCKING) ---
  //
  // A draft is valid in two states: before injection it carries exactly one
  // [[content_image]] placeholder; after injection it carries none but has a real
  // <img>. Demanding exactly one placeholder wrongly blocked finished articles.
  const structureFindings: string[] = [];
  const placeholders = (html.match(/\[\[content_image\]\]/g) ?? []).length;
  const hasImage = hasInlineImage(html);
  if (placeholders > 1) {
    structureFindings.push(
      `found ${placeholders} [[content_image]] placeholders; use exactly one`,
    );
  } else if (placeholders === 0 && !hasImage) {
    structureFindings.push(
      'no [[content_image]] placeholder and no inline <img> — the article has no in-body image',
    );
  }
  const headings = [...html.matchAll(/<h([23])[^>]*>/gi)].map((m) => Number(m[1]));
  if (headings.length > 0 && headings[0] === 3) {
    structureFindings.push('article starts with an H3 before any H2');
  }
  checks.push({
    name: 'structure',
    ok: structureFindings.length === 0,
    blocking: true,
    detail:
      structureFindings.length === 0 ? 'Structure is valid' : `${structureFindings.length} issue(s)`,
    findings: structureFindings,
  });

  // --- Images (advisory) ---
  //
  // NON-BLOCKING on purpose. The working order is brief → write → score →
  // generate images → publish, so at score time there is usually no feature
  // image yet and often no inline <img> either. A blocking check here would
  // make the normal order impossible to satisfy.
  //
  // This check verifies PRESENCE and ALT TEXT only. It cannot verify what is
  // in an image — whether it shows people, whether it relates to the article —
  // because that is not derivable from HTML, and pretending otherwise would be
  // worse than not checking. The photographic contract itself is enforced in
  // src/craft/image-style.ts and by generate_image.
  const imageFindings: string[] = [];

  if (feature) {
    const alt = feature.alt?.trim() ?? '';
    if (alt === '') {
      imageFindings.push(
        'the feature image has no alt text — it is what a screen-reader user gets instead of the photograph',
      );
    } else if (feature.title && restatesTitle(alt, feature.title)) {
      imageFindings.push(
        'the feature image alt text restates the article title; describe what is visible in the frame instead',
      );
    }
  }

  // An <img> with no alt at all, or alt="", inside the body. Decorative images
  // legitimately use alt="", but nothing this pipeline produces is decorative:
  // every in-body image is a generated photograph carrying meaning.
  for (const tag of html.match(/<img\s[^>]*>/gi) ?? []) {
    const altAttr = /\salt\s*=\s*(["'])(.*?)\1/i.exec(tag);
    if (!altAttr || altAttr[2]!.trim() === '') {
      imageFindings.push('an in-body image has empty or missing alt text');
      break;
    }
  }

  const featureState = feature ? 'feature image checked' : 'no feature image passed — not evaluated';
  checks.push({
    name: 'images',
    ok: imageFindings.length === 0,
    blocking: false,
    detail: `${featureState}; presence and alt text only — this check cannot verify what an image actually depicts`,
    findings: imageFindings,
  });

  // --- AI summary block (BLOCKING) ---
  //
  // A visual summary block must sit above the first H2, and must use a container
  // that survives ingest with its styling — on Ghost a <div> card would be
  // stripped to bare text.
  const firstH2 = html.search(/<h2[\s>]/i);
  const preamble = firstH2 === -1 ? html : html.slice(0, firstH2);
  // Every container the profile accepts — no hardcoded tag here. `blockquote`
  // is in Ghost's list because a native one survives (unstyled); appending it
  // in this file would put platform knowledge straight back into craft/.
  const hasSummaryBlock = profile.visualContainers.some((tag) =>
    new RegExp(`<${tag}[\\s>]`, 'i').test(preamble),
  );
  // Name a tag the platform actually unwraps, so the writer knows *why* the
  // container matters — a div-based card doesn't error, it just quietly
  // publishes as unstyled text. Taken from the profile, not hardcoded, so it
  // stays correct for any platform's unwrapped set.
  //
  // No `?? 'div'` fallback: a profile can legitimately have an EMPTY
  // `unwrapped` set (WordPress, for an account holding unfiltered_html —
  // nothing is unwrapped on ingest for that account). Fabricating "div" in
  // that case produced a self-contradicting, factually inverted message —
  // "a <div> card would be stripped" on the one platform where <div> is
  // exactly what survives. When nothing is unwrapped, there is no tag to
  // warn against, so the parenthetical is omitted entirely rather than
  // inventing one.
  const firstUnwrapped = profile.unwrapped.size > 0 ? [...profile.unwrapped][0] : undefined;
  const summaryBlockAdvice = container
    ? firstUnwrapped
      ? `Add a styled <${container}> summary block above the first H2 (a <${firstUnwrapped}> card would be stripped).`
      : `Add a styled <${container}> summary block above the first H2.`
    : 'Add a summary block above the first H2.';
  checks.push({
    name: 'ai_summary_block',
    ok: hasSummaryBlock,
    blocking: true,
    detail: hasSummaryBlock
      ? 'Summary block present before the first H2'
      : 'No summary block before the first H2',
    findings: hasSummaryBlock
      ? []
      : [
          summaryBlockAdvice,
        ],
  });

  // --- AEO: is the article answerable? (advisory) ---
  const headingTexts = [...html.matchAll(/<h[234][^>]*>(.*?)<\/h[234]>/gis)].map((m) =>
    stripTags(m[1] ?? ''),
  );
  const questionHeadings = headingTexts.filter((h) => h.trim().endsWith('?'));
  const aeoOk = questionHeadings.length >= 2;
  checks.push({
    name: 'aeo_answerability',
    ok: aeoOk,
    blocking: false,
    score: questionHeadings.length,
    detail: `${questionHeadings.length} question-form heading(s) of ${headingTexts.length} (target >= 2)`,
    findings: aeoOk
      ? []
      : [
          'Answer engines lift Q&A pairs. Phrase at least two headings as the question a reader would type, and answer it in the first 40-60 words underneath.',
        ],
  });

  // --- GEO: can a model cite this? (advisory) ---
  //
  // Generative engines quote attributed, self-contained claims. Count sentences
  // that name a source and carry a verb of attribution.
  const attributions = (
    text.match(
      /\b(according to|per|reports?|reported|found that|survey(?:ed)?|study|research|data from|figures from|says?|said)\b/gi,
    ) ?? []
  ).length;
  const geoOk = attributions >= 3;
  checks.push({
    name: 'geo_citability',
    ok: geoOk,
    blocking: false,
    score: attributions,
    detail: `${attributions} attributed claim marker(s) (target >= 3)`,
    findings: geoOk
      ? []
      : [
          'Generative engines cite what they can attribute. Name the source and the date inline ("According to Deloitte\'s 2024 study...") rather than asserting figures bare.',
        ],
  });

  // --- Citation provenance (advisory) ---
  //
  // The first check in this project that can verify a claim's PROVENANCE
  // rather than its shape. Deliberately separate from `geo_citability`:
  // that one asks "does this attribute its claims at all", this one asks "do
  // the cited URLs come from the research set". One check answering two
  // questions is how SLUG_PATTERN and IMAGE_LOOKS drifted.
  //
  // Advisory, not blocking: a writer legitimately links a homepage, a docs
  // page, or a definition that no search returned. Blocking would forbid every
  // non-research link.
  //
  // With no findings this reports "not evaluated" rather than ok — the same
  // honesty as the feature-image check. A silent pass would read as "the
  // citations were verified" when nothing was.
  const provenanceFindings: string[] = [];
  let provenanceDetail: string;

  // `findings?.length` rather than `findings`: an empty array is a real
  // research_topic outcome (a caller who threads the field through
  // unconditionally can produce one), and it can verify nothing — same
  // honesty as the absent case, not "0 traceable of 0".
  if (!findings || findings.length === 0) {
    provenanceDetail = 'no research findings passed — not evaluated, no citation was verified';
  } else {
    const researchUrls = new Set(findings.map((f) => sameUrl(f.url)));
    // Both quote styles, matching the precedent set by the alt-text regex
    // below — a single-quoted href is exactly as valid HTML as a
    // double-quoted one and should not be invisible to this check.
    //
    // Two alternatives rather than one pattern with a `(["'])...\1`
    // backreference: the backreference version excludes BOTH quote
    // characters from the captured value regardless of which one opened
    // the attribute, so a literal `'` inside a double-quoted href (valid
    // HTML, and it shows up in real query strings) breaks the
    // backreference match and silently drops the whole anchor. Each
    // alternative below only excludes the quote that actually delimits it,
    // so a `'` survives inside `"..."` and a `"` survives inside `'...'`.
    const citedRaw = [...html.matchAll(/<a\s[^>]*\bhref\s*=\s*(?:"(https?:\/\/[^">]+)"|'(https?:\/\/[^'>]+)')/gi)].map(
      (m) => decodeHtmlEntities((m[1] ?? m[2])!),
    );
    const cited = new Map(citedRaw.map((raw) => [sameUrl(raw), raw]));

    // Count distinct normalised URLs on both sides of the sentence below —
    // `citedRaw.length` counted duplicates, which made a URL cited twice
    // report an arithmetically self-contradictory "traceable" figure.
    let invented = 0;
    for (const [norm, raw] of cited) {
      if (!researchUrls.has(norm)) {
        invented++;
        provenanceFindings.push(
          `cited URL is not in the research set: ${raw} — if a claim rests on it, it cannot be traced to the research this article was grounded in`,
        );
      }
    }
    const uncited = findings.filter((f) => !cited.has(sameUrl(f.url)));
    for (const f of uncited) {
      provenanceFindings.push(`research source never cited: ${f.url} (${f.title})`);
    }
    const traceable = cited.size - invented;
    provenanceDetail = `${cited.size} cited URL(s) against ${findings.length} research source(s); ${traceable} traceable, ${uncited.length} source(s) unused`;
  }

  checks.push({
    name: 'citation_provenance',
    ok: provenanceFindings.length === 0,
    blocking: false,
    detail: provenanceDetail,
    findings: provenanceFindings,
  });

  const blocked = checks.some((c) => c.blocking && !c.ok);
  const advisory = checks.some((c) => !c.blocking && !c.ok);

  return {
    verdict: blocked ? 'blocked' : advisory ? 'revise' : 'pass',
    wordCount: words,
    checks,
  };
}
